version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run: python setup.py install
      - run:
          command: |
            export DJANGO_SETTINGS_MODULE=tests.settings
            python -m django migrate
            python -m django test
  build_and_deploy:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          command: |
            pip install twine bumpversion
            python setup.py install
      - run:
          command: |
              git config  user.email "dev@stitchdesignlab.com"
              git config  user.name "Dev Bot"
      - run: bumpversion patch setup.py
      - run:
          command: |
            python setup.py sdist
            twine upload dist/*
      - run:
          command: |
            git push origin ${CIRCLE_BRANCH}
            git push origin ${CIRCLE_BRANCH} --tags
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - production